export const AUDIO_SAMPLE_RATE = '16000';
export const AUDIO_SAMPLE_FORMAT = 's16le';
export const AUDIO_CHANNELS = '1';
export const MIN_AUDIO_DURATION_MS = 1000;
export const MAX_AUDIO_DURATION_MS = 20000;

export const MAX_PCM_AUDIO_BODY_BYTES =
  (Number(AUDIO_SAMPLE_RATE) * 2 * MAX_AUDIO_DURATION_MS) / 1000;
export const MIN_PCM_AUDIO_BODY_BYTES =
  (Number(AUDIO_SAMPLE_RATE) *
    Number(AUDIO_CHANNELS) *
    2 *
    MIN_AUDIO_DURATION_MS) /
  1000;

export const AUDIO_BODY_TOLERANCE_BYTES = 4096;
export const MAX_AUDIO_BODY_BYTES =
  MAX_PCM_AUDIO_BODY_BYTES + AUDIO_BODY_TOLERANCE_BYTES;
